name: Update Photos from Google Photos

on:
  schedule:
    # Run once a week on Sunday at 01:00 UTC
    - cron: '0 1 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-photos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install googleapis
          
      - name: Create config directory
        run: mkdir -p config
        
      - name: Set up Google credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > config/google-credentials.json
          echo '${{ secrets.GOOGLE_TOKEN }}' > config/google-token.json
        
      - name: Update photos configuration
        run: node scripts/update-photos.js
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update photos config" && git push)